apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: exam
spec:
  serviceName: mysql-service
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: "500m" # 0.5 CPU
              memory: "512Mi" # 512 Megabytes
            requests:
              cpu: "250m" # 0.25 CPU
              memory: "256Mi" # 256 Megabytes
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: exam
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: exam
type: Opaque
data:
  root-password: MTIzNDU2
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: mysql-pdb
  namespace: exam
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: mysql
