apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resource-access-binding
  namespace: exam
subjects:
  - kind: User
    name: zakariaamensar
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: resource-access-role
  apiGroup: rbac.authorization.k8s.io
