apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: exam
  name: resource-access-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
